### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by TaylorBrown96** [TaylorBrown96/Ring_Wars#35]
- [ ] Items, mobs, and rooms should contain a consistent theme across the game play
- [ ] Dialog and interactions with the player should strengthen the story telling
- [ ] A written player storyline with the completion goals in order to win the game

Possibly an Easter Egg if the user does something unique?
